name: firebase_core_platform_interface
description: A common platform interface for the firebase_core plugin.
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 7.0.1
publish_to: none

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  # Needed to export the mocks
  flutter_test:
    sdk: flutter
  meta: ^1.18.3
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  mockito: ^5.7.0
  pigeon:
    git: https://github.com/kumsumit/pigeon.git
