name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://firebase.google.com/docs/cloud-messaging
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging
version: 16.3.0
publish_to: none
topics:
  - firebase
  - messaging
  - notifications

false_secrets:
  - example/**

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  firebase_core:
    git: "https://github.com/kumsumit/firebase_core.git"
  firebase_core_platform_interface:
    git: "https://github.com/kumsumit/firebase_core_platform_interface.git"
  firebase_messaging_platform_interface: 
    git: "https://github.com/kumsumit/firebase_messaging_platform_interface.git"
  firebase_messaging_web: 
    git: "https://github.com/kumsumit/firebase_messaging_web.git"
  flutter:
    sdk: flutter
  meta: ^1.18.3

dev_dependencies:
  async: ^2.13.1
  flutter_test:
    sdk: flutter
  mockito: ^5.7.0
  plugin_platform_interface:
    git: "https://github.com/kumsumit/plugin_platform_interface.git"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
