name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.
publish_to: none

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  firebase_analytics:
    git: https://github.com/kumsumit/firebase_analytics.git
  firebase_core:
    git: https://github.com/kumsumit/firebase_core.git
  firebase_crashlytics:
    git: https://github.com/kumsumit/firebase_crashlytics.git
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
