name: firebase_analytics_platform_interface
description: A common platform interface for the firebase_analytics plugin.
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_platform_interface
version: 6.0.2
publish_to: none

environment:
  sdk: '^3.12.0'
  flutter: '>=3.44.0'

dependencies:
  _flutterfire_internals:
    git: https://github.com/kumsumit/_flutterfire_internals.git
  firebase_core: 
    git: https://github.com/kumsumit/firebase_core.git
  flutter:
    sdk: flutter
  meta: ^1.18.3
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  firebase_core_platform_interface:
    git: https://github.com/kumsumit/firebase_core_platform_interface.git
  flutter_test:
    sdk: flutter
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git
